<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OBDim</AssemblyName>
    <RootNamespace>OBDim</RootNamespace>
    <Version>1.0.2</Version>
    <ApplicationIcon>assets\obdim.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\icon-work.ico" />
    <EmbeddedResource Include="assets\icon-away.ico" />
    <EmbeddedResource Include="assets\icon-unknown.ico" />
  </ItemGroup>

</Project>
